# Generated by Django 5.2.6 on 2025-09-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_DB',
            fields=[
                ('Car_Name', models.CharField(max_length=12)),
                ('Car_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.CharField()),
                ('Price', models.FloatField()),
                ('Color', models.CharField()),
            ],
        ),
    ]
